INSERT INTO cloth_sugg (sugg_text, uv_level, temp_level, is_raining) VALUES
('UV is low today. It is cold and raining. We recommend bringing sunglasses, long sleeves, long pants, and an umbrella.', 'low', 'cold', true),
('UV is low today. It is cold outside. We recommend wearing long sleeves and long pants, and bringing sunglasses.', 'low', 'cold', false),
('UV is low today. The temperature is mild and it is raining. We recommend bringing sunglasses, a long sleeve, and an umbrella.', 'low', 'mild', true),
('UV is low today. The temperature is mild. We recommend bringing sunglasses and wearing a long sleeve.', 'low', 'mild', false),
('UV is low today. It is warm outside and raining. We recommend bringing sunglasses and an umbrella.', 'low', 'warm', true),
('UV is low today. It is warm outside. We recommend bringing sunglasses.', 'low', 'warm', false),
('UV is moderate today. It is cold and raining. We recommend bringing sunglasses, a hat, long sleeves, long pants, and an umbrella.', 'moderate', 'cold', true),
('UV is moderate today. It is cold outside. We recommend wearing long sleeves and long pants, and bringing sunglasses and a hat.', 'moderate', 'cold', false),
('UV is moderate today. The temperature is mild and it is raining. We recommend bringing sunglasses, a hat, a long sleeve, and an umbrella.', 'moderate', 'mild', true),
('UV is moderate today. The temperature is mild. We recommend bringing sunglasses, a hat, and wearing a long sleeve.', 'moderate', 'mild', false),
('UV is moderate today. It is warm outside and raining. We recommend bringing sunglasses, a hat, and an umbrella.', 'moderate', 'warm', true),
('UV is moderate today. It is warm outside. We recommend bringing sunglasses and a hat.', 'moderate', 'warm', false),
('UV is high today. It is cold and raining. We recommend bringing sunglasses, a hat, long sleeves, long pants, and an umbrella.', 'high', 'cold', true),
('UV is high today. It is cold outside. We recommend wearing long sleeves and long pants, and bringing sunglasses and a hat.', 'high', 'cold', false),
('UV is high today. The temperature is mild and it is raining. We recommend bringing sunglasses, a hat, a long sleeve, and an umbrella.', 'high', 'mild', true),
('UV is high today. The temperature is mild. We recommend bringing sunglasses, a hat, and wearing a long sleeve.', 'high', 'mild', false),
('UV is high today. It is warm outside and raining. We recommend bringing sunglasses, a hat, a long sleeve, and an umbrella.', 'high', 'warm', true),
('UV is high today. It is warm outside. We recommend bringing sunglasses, a hat, and a long sleeve.', 'high', 'warm', false),
('UV is very high today. It is cold and raining. We strongly recommend bringing sunglasses, a hat, long sleeves, long pants, an umbrella, and applying sunscreen.', 'very_high', 'cold', true),
('UV is very high today. It is cold outside. We strongly recommend wearing long sleeves and long pants, bringing sunglasses and a hat, and applying sunscreen.', 'very_high', 'cold', false),
('UV is very high today. The temperature is mild and it is raining. We strongly recommend bringing sunglasses, a hat, long sleeves, long pants, an umbrella, and applying sunscreen.', 'very_high', 'mild', true),
('UV is very high today. The temperature is mild. We strongly recommend bringing sunglasses, a hat, long sleeves, long pants, and applying sunscreen.', 'very_high', 'mild', false),
('UV is very high today. It is warm outside and raining. We strongly recommend bringing sunglasses, a hat, long sleeves, long pants, an umbrella, and applying sunscreen.', 'very_high', 'warm', true),
('UV is very high today. It is warm outside. We strongly recommend bringing sunglasses, a hat, long sleeves, long pants, and applying sunscreen.', 'very_high', 'warm', false),
('UV is extreme today. It is cold and raining. UV radiation is dangerously high — going outside is not recommended. If you must go out, bring sunglasses, a hat, long sleeves, long pants, an umbrella, and apply high-SPF sunscreen.', 'extreme', 'cold', true),
('UV is extreme today. It is cold outside. UV radiation is dangerously high — going outside is not recommended. If you must go out, wear long sleeves and long pants, bring sunglasses and a hat, and apply high-SPF sunscreen.', 'extreme', 'cold', false),
('UV is extreme today. The temperature is mild and it is raining. UV radiation is dangerously high — going outside is not recommended. If you must go out, bring sunglasses, a hat, long sleeves, long pants, an umbrella, and apply high-SPF sunscreen.', 'extreme', 'mild', true),
('UV is extreme today. The temperature is mild. UV radiation is dangerously high — going outside is not recommended. If you must go out, bring sunglasses, a hat, long sleeves, long pants, and apply high-SPF sunscreen.', 'extreme', 'mild', false),
('UV is extreme today. It is warm outside and raining. UV radiation is dangerously high — going outside is not recommended. If you must go out, bring sunglasses, a hat, long sleeves, an umbrella, and apply high-SPF sunscreen.', 'extreme', 'warm', true),
('UV is extreme today. It is warm outside. UV radiation is dangerously high — going outside is not recommended. If you must go out, bring sunglasses, a hat, long sleeves, and apply high-SPF sunscreen.', 'extreme', 'warm', false);